### ISSUE TITLE
clojurians.net is down

### ISSUE THREAD

**Issue by endc42** [clojurians/clojurians-website#1]
Navigating to clojurians.net shows the following:

![screen shot 2016-11-07 at 10 49 52](https://cloud.githubusercontent.com/assets/19195422/20066672/03432494-a4d8-11e6-9c1c-c793d58b8d4c.png)

Best,
E

**Comment by xykj61** [comment]
Shows up for me too.

**Comment by endc42** [comment]
This has come back up, so I'll close this.

**Comment by seancorfield** [comment]
It seems to be down again right now.

**Comment by seancorfield** [comment]
clojurians.net is back up.
