### ISSUE TITLE
clojurians.net is down

### ISSUE THREAD

**Issue by AlJohri** [clojurians/clojurians-website#2]
http://clojurians.net/

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

cc @adulteratedjedi @martinklepsch @pkobrien @mollyocr

**Comment by gjnoonan** [comment]
@AlJohri Thank you for raising this. I have just looked and the site appears to be up. I shall have a look through the logs and see what occurred.

**Comment by AlJohri** [comment]
Working for me now as well. Weird! I got the error repeatedly for 5 minutes or so. Thanks for the quick response!
