### ISSUE TITLE
Trying to join, but no email is sent and the Slack redirect stalls.

### ISSUE THREAD

**Issue by cadillion** [clojurians/clojurians-website#3]
I submit my email, but a verification email never arrives.

I've tried running Chrome Version 56.0.2924.87 with all extensions disabled, and in Incognito Mode. In this case, the button says it is redirecting to slack but the redirect never happens.

I've also tried Microsoft Edge 38.14393.0.0 and Internet Explorer Version 11.953.14393.0. In these cases, the button stalls at PLEASE WAIT.

I am running Windows 10.

**Comment by gjnoonan** [comment]
@cadillion I am really sorry about this, could you PM me your email, and I shall add you manually.

Many thanks
