### ISSUE TITLE
Add a badge for clojurians slack join

### ISSUE THREAD

**Issue by jerger** [clojurians/clojurians-website#4]
Would be cool, if I could add sth. like
`[![Slack](http://community-slack.chef.io/badge.svg)](https://clojurians.herokuapp.com/)` to my github readme's.

**Comment by seancorfield** [comment]
Just FYI, the link we normally give out for signup is http://clojurians.net/ (non-SSL tho').

**Comment by jerger** [comment]
will fix this on my side :-)

**Comment by martinklepsch** [comment]
How about this?

```markdown
[![Slack](https://img.shields.io/badge/chat-clojurians-green.svg?style=flat)](http://clojurians.net)
```

 [![Slack](https://img.shields.io/badge/chat-clojurians-green.svg?style=flat)](http://clojurians.net)

**Comment by jerger** [comment]
Like it : -)

See: https://github.com/DomainDrivenArchitecture/dda-serverspec-crate/tree/development
